<a href="https://colab.research.google.com/github/DJunichiR/Desain-Analisis-Algoritma/blob/main/Desain_Analisis_Algoritma_PERTEMUAN_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#UNTUK MENAMPILKAN DATA DI DALAM LIST
import numpy as np
import datetime
tanggal = datetime.date.today ()


aList_nama = ["Dapa",
              "2022071006",
              "Informatika",
              "Desain Analisis Algoritma",
              str(tanggal),
              "Universitas Pembangunan Jaya"]
print(aList_nama)

['Dapa', '2022071006', 'Informatika', 'Desain Analisis Algoritma', '2023-09-13', 'Universitas Pembangunan Jaya']


In [ ]:
import numpy as np

bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
bin_colors[-1] #kalo pake - jadi ngitung dari belakang

'Yellow'

In [ ]:
import numpy as np
import datetime
tanggal = datetime.date.today ()


aList_nama = ["Daffa Junichi Rahmadi",  "2022071006", "Informatika", "Desain Analisis Algoritma", str(tanggal), "Universitas Pembangunan Jaya"]
print("NIM Daffa Junichi Rahmadi : ", aList_nama[1])  #UNTUK MENAMPILKAN NIM NYA SAJA


NIM Daffa Junichi Rahmadi :  2022071006


In [ ]:
import numpy as np

bin_colors = ['Red', 'Green', 'Blue', 'Yellow', "White", "Black", "Grey"]
bin_colors[0:3] #MENAMPILKAN 3 DATA DIMULAI DARI 0 DISEBUTNYA SLICING


['Red', 'Green', 'Blue']

In [ ]:
bin_colors=["Red","Green","Blue","Yellow"]
for aColor in bin_colors:
  print(aColor + "Square")

RedSquare
GreenSquare
BlueSquare
YellowSquare


In [ ]:
import numpy as np
import datetime
tanggal = datetime.date.today ()


aList_nama = ["Dapa",  "2022071006", "Informatika", "Desain Analisis Algoritma", str(tanggal), "Universitas Pembangunan Jaya"]
for Mahasiswa in aList_nama:
    print("UPJ " + Mahasiswa) #UNTUK MENAMBAH KATA "UPJ" KE DALAM LIST YANG SUDAH DIBUAT

UPJ Dapa
UPJ 2022071006
UPJ Informatika
UPJ Desain Analisis Algoritma
UPJ 2023-09-13
UPJ Universitas Pembangunan Jaya


In [ ]:
#NESTED TUPLE
Pertama=("100")
Kedua=("200", "400", "600")
Ketiga=("300")
Keempat=("400", "800")
Total = (Pertama,Kedua,Ketiga,Keempat)
print(Total)

('100', ('200', '400', '600'), '300', ('400', '800'))


In [ ]:
#DICTIONARY
import numpy as np

bin_mahasiswa = {"NAMA"  :"Dapa",
              "NIM " : "2022071006",
              "Prodi " : "Informatika",
              "Mata Kuliah" : "Desain Analisis Algoritma",
              "Universitas" : "Universitas Pembangunan Jaya"}
print(bin_mahasiswa)

SyntaxError: ignored

In [ ]:
#Inisiasi Set
set_01 = {4,5,6,2}
print("set_01 = ", set_01)

#inisiasi mengubah list menjadi set
set_02 = set()
set_03 = set([2,1,4,3])

print(type(set_02))
print("set_03 = ", set_03)

print("\nmenambah")
set_01.add(576)
print(set_01)

print("\nmenghapus")
set_01.discard(6)
print(set_01)

print("\nunion")
print(set_01|set_03)
print("\nintersection")
print(set_01&set_03)

print("\ndifference")
print(set_01-set_03)

print("\nsymmetric difference")
print(set_01^set_03)

set_01 =  {2, 4, 5, 6}
<class 'set'>
set_03 =  {1, 2, 3, 4}

menambah
{576, 2, 4, 5, 6}

menghapus
{576, 2, 4, 5}

union
{576, 1, 2, 3, 4, 5}

intersection
{2, 4}

difference
{576, 5}

symmetric difference
{576, 1, 3, 5}


In [ ]:
red = {"dandelions", "leaves", "fire hydrant"}
green = {"rose", "blood", "leaves", "fire hydrant"}

print(red|green)
print(red&green)

{'dandelions', 'blood', 'leaves', 'rose', 'fire hydrant'}
{'leaves', 'fire hydrant'}


In [ ]:
import numpy as np

matrix = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800]
    ])

print(matrix)

print("\nTranspose:")
print(matrix.T)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]

Transpose:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [ ]:
import pandas as pd

df = pd.DataFrame([
    [1, "Informatika", 50, 30, 20],
    [2, "Sistem Informasi", 55, 30, 25],
    [3, "Teknik Sipil", 40, 30, 10]
])

df.columns = ["No", "Prodi", "Mahasiswa", "laki-laki", "Perempuan"]
df.style.hide(axis='index')